//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table5
    {
        public System.DateTime Date { get; set; }
        public string Symbol { get; set; }
        public Nullable<decimal> Open { get; set; }
        public Nullable<decimal> High { get; set; }
        public Nullable<decimal> Low { get; set; }
        public Nullable<decimal> Close { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> AdjClose { get; set; }
        public Nullable<decimal> Returns { get; set; }
        public Nullable<decimal> RollingAverage { get; set; }
        public Nullable<decimal> RollingStd { get; set; }
        public Nullable<decimal> ZscoreStatic { get; set; }
        public Nullable<decimal> ZscoreRolling { get; set; }
        public Nullable<decimal> PositionStatic { get; set; }
        public Nullable<decimal> PNLstatic { get; set; }
        public Nullable<decimal> CumPNLstatic { get; set; }
        public Nullable<decimal> RealPNLstatic { get; set; }
        public Nullable<decimal> CumRealPNLstatic { get; set; }
        public Nullable<decimal> PositionsStaticHold { get; set; }
        public Nullable<decimal> PNLstaticHold { get; set; }
        public Nullable<decimal> CumPNLstaticHold { get; set; }
        public Nullable<decimal> RealPNLstaticHold { get; set; }
        public Nullable<decimal> CumRealPNLstaticHold { get; set; }
        public Nullable<decimal> PositionsRoll { get; set; }
        public Nullable<decimal> PNLroll { get; set; }
        public Nullable<decimal> CumPNLroll { get; set; }
        public Nullable<decimal> RealPNLroll { get; set; }
        public Nullable<decimal> CumRealPNLroll { get; set; }
        public Nullable<decimal> PositionsRollHold { get; set; }
        public Nullable<decimal> PNLrollHold { get; set; }
        public Nullable<decimal> CumPNLrollHold { get; set; }
        public Nullable<decimal> RealPNLrollHold { get; set; }
        public Nullable<decimal> CumRealPNLrollHold { get; set; }
    }
}
